version: '{build}'

environment:
  APP_NAME: nimjson
  MINGW_DIR: mingw64
  MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
  MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
  NIM_DIR: nim-0.19.6
  NIM_URL: https://nim-lang.org/download/nim-0.19.6_x64.zip
  NIM_ARCHIVE: nim-0.19.6_x64.zip
  platform: x64

cache:
    - '%MINGW_ARCHIVE%'
    - '%NIM_ARCHIVE%'

matrix:
  fast_finish: true

install:
  - MKDIR %CD%\DIST
  - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" -o"%CD%\DIST"> nul
  - IF not exist "%NIM_ARCHIVE%" appveyor DownloadFile "%NIM_URL%" -FileName "%NIM_ARCHIVE%"
  - 7z x -y "%NIM_ARCHIVE%" -o"%CD%\DIST"> nul
  - SET PATH=%CD%\DIST\%NIM_DIR%\BIN;%CD%\DIST\%MINGW_DIR%\BIN;%CD%\BIN;%PATH%

build: off

build_script:
  - nimble ci
  - mkdir %APP_NAME%_windows
  - xcopy bin %APP_NAME%_windows\bin\
  - copy README.adoc %APP_NAME%_windows\
  - copy LICENSE %APP_NAME%_windows\
  - 7z a %APP_NAME%_windows.zip %APP_NAME%_windows

artifacts:
  - path: '*_windows.zip'
    name: zip

deploy:
- provider: GitHub
  auth_token:
    secure: esSlDbpH2rczLbaAJm5b1tG1KfwaQ6POEICFbpY7oJkW++IrNwJFpz6O5oyoAe/7
  artifacts: zip
  on:
    branch: master
    appveyor_repo_tag: true 
